export const types = {
  GET_RECIPES: 'GET_RECIPES',
  GET_RECIPE_INFO: 'GET_RECIPE_INFO',
  GET_FAVORITE_RECIPES: 'GET_FAVORITE_RECIPES',
  SET_FAVORITE_RECIPES: 'SET_FAVORITE_RECIPES',
  REMOVE_FAVORITE_RECIPE: 'REMOVE_FAVORITE_RECIPE',
};
